### ISSUE TITLE
老哥，opwrt怎么用

### ISSUE THREAD

**Issue by hackerlengyue** [v03413/ServerStatus-Client#1]
老哥，opwrt怎么用

**Comment by v03413** [comment]
> 老哥，opwrt怎么用

如果是x86 或者 arm v8的，直接下载release 对应版本，配合 nohup + 开机自启 即可

---  

最近比较忙，有空再写个 makefile

**Comment by v03413** [comment]
> 老哥，opwrt怎么用

已更新文档，https://github.com/v03413/ServerStatus-Client/commit/8d0e9509e563f3357ed27a6f16f7eae1e25575d7
