### ISSUE TITLE
windows 下关于得到 tcp，udp 和 进程数的探讨

### ISSUE THREAD

**Issue by CHN-STUDENT** [v03413/ServerStatus-Client#2]
RT，最近还在研究如何写跨平台监控，但是我看您没写 windows 下监控这些的办法。
我用的gorouter 不停执行  `exec.Cmd` 和 `exec.Output ` 通过` cmd /c netstat ` 实现了，但是后期会一直报错。
```
fork/exec C:\\Windows\\system32\\cmd.exe: Operation did not complete successfully because the file contains a virus or potentially unwanted software.
```
不知道老哥有没有什么想法可以探讨？

**Comment by v03413** [comment]
我现在已经不怎么用 windows，对于这个问题也没研究过。    

---  
Ps：其实当时我在写的时候也在想，应该没几个会在win 下面挂探针吧...

**Comment by CHN-STUDENT** [comment]
加了一个` exec.Process().Kill()` ，目前暂时没啥问题....
我司还有不少服务器还是 win server 的，所以还要监控。
此外 cppla 那个版本只能用 linux 做 server 端，我又不会 c++，只能学 golang 重写。
