### ISSUE TITLE
想了解下releases的用法

### ISSUE THREAD

**Issue by ReibyouGennsei** [v03413/ServerStatus-Client#3]
releases实在没看明白要怎么运行起来，是x86的路由
想编译一个，发现没有error，但是不生成ipk
`s@s-virtual-machine:~/lede$ make package/ServerStatus-Client/compile -j1 V=99
time: target/linux/prereq#0.07#0.03#0.10
make[1]: Entering directory '/home/s/lede'
make[2]: Entering directory '/home/s/lede/feeds/packages/lang/golang/golang'
mkdir -p /home/s/lede/dl
SHELL= flock /home/s/lede/tmp/.go1.4-bootstrap-20171003.tar.gz.flock -c '       /home/s/lede/scripts/downlo                ad.pl "/home/s/lede/dl" "go1.4-bootstrap-20171003.tar.gz" "f4ff5b5eb3a3cae1c993723f3eab519c5bae18866b5e5f96                fe1102f0cb5c3e52" "" "https://dl.google.com/go/" "https://mirrors.ustc.edu.cn/golang/" "https://mirrors.nju                .edu.cn/golang/"    '
mkdir -p /home/s/lede/dl
SHELL= flock /home/s/lede/tmp/.go1.18.4.src.tar.gz.flock -c '   /home/s/lede/scripts/download.pl "/home/s/l                ede/dl" "go1.18.4.src.tar.gz" "4525aa6b0e3cecb57845f4060a7075aafc9ab752bb7b6b4cf8a212d43078e1e4" "" "https:                //dl.google.com/go/" "https://mirrors.ustc.edu.cn/golang/" "https://mirrors.nju.edu.cn/golang/"    '
make[2]: Leaving directory '/home/s/lede/feeds/packages/lang/golang/golang'
time: package/feeds/packages/golang/host-compile#0.25#0.29#0.50
make[2]: Entering directory '/home/s/lede/package/libs/toolchain'
echo "libc" >> /home/s/lede/staging_dir/target-x86_64_musl/pkginfo/toolchain.default.install
echo "libgcc" >> /home/s/lede/staging_dir/target-x86_64_musl/pkginfo/toolchain.default.install
echo "libstdcpp" >> /home/s/lede/staging_dir/target-x86_64_musl/pkginfo/toolchain.default.install
echo "libpthread" >> /home/s/lede/staging_dir/target-x86_64_musl/pkginfo/toolchain.default.install
echo "librt" >> /home/s/lede/staging_dir/target-x86_64_musl/pkginfo/toolchain.default.install
make[2]: Leaving directory '/home/s/lede/package/libs/toolchain'
time: package/libs/toolchain/compile#0.11#0.03#0.14
make[2]: Entering directory '/home/s/lede/package/system/ca-certificates'
mkdir -p /home/s/lede/dl
SHELL= flock /home/s/lede/tmp/.ca-certificates_20210119.tar.xz.flock -c '       /home/s/lede/scripts/downlo                ad.pl "/home/s/lede/dl" "ca-certificates_20210119.tar.xz" "daa3afae563711c30a0586ddae4336e8e3974c2b627faaca                404c4e0141b64665" "" "@DEBIAN/pool/main/c/ca-certificates"    '
echo "ca-bundle" >> /home/s/lede/staging_dir/target-x86_64_musl/pkginfo/ca-certificates.default.install
echo "ca-certificates" >> /home/s/lede/staging_dir/target-x86_64_musl/pkginfo/ca-certificates.default.insta                ll
make[2]: Leaving directory '/home/s/lede/package/system/ca-certificates'
time: package/system/ca-certificates/compile#0.14#0.03#0.17
make[2]: Entering directory '/home/s/lede/package/feeds/packages/ServerStatus-Client'
make[2]: Leaving directory '/home/s/lede/package/feeds/packages/ServerStatus-Client'
time: package/feeds/packages/ServerStatus-Client/compile#0.10#0.02#0.12
make[1]: Leaving directory '/home/s/lede'
s@s-virtual-machine:~/lede$
`

**Comment by v03413** [comment]
> releases实在没看明白要怎么运行起来，是x86的路由 想编译一个，发现没有error，但是不生成ipk `s@s-virtual-machine:~/lede$ make package/ServerStatus-Client/compile -j1 V=99 time: target/linux/prereq#0.07#0.03#0.10 make[1]: Entering directory '/home/s/lede' make[2]: Entering directory '/home/s/lede/feeds/packages/lang/golang/golang' mkdir -p /home/s/lede/dl SHELL= flock /home/s/lede/tmp/.go1.4-bootstrap-20171003.tar.gz.flock -c ' /home/s/lede/scripts/downlo ad.pl "/home/s/lede/dl" "go1.4-bootstrap-20171003.tar.gz" "f4ff5b5eb3a3cae1c993723f3eab519c5bae18866b5e5f96 fe1102f0cb5c3e52" "" "https://dl.google.com/go/" "https://mirrors.ustc.edu.cn/golang/" "https://mirrors.nju .edu.cn/golang/" ' mkdir -p /home/s/lede/dl SHELL= flock /home/s/lede/tmp/.go1.18.4.src.tar.gz.flock -c ' /home/s/lede/scripts/download.pl "/home/s/l ede/dl" "go1.18.4.src.tar.gz" "4525aa6b0e3cecb57845f4060a7075aafc9ab752bb7b6b4cf8a212d43078e1e4" "" "https: //dl.google.com/go/" "https://mirrors.ustc.edu.cn/golang/" "https://mirrors.nju.edu.cn/golang/" ' make[2]: Leaving directory '/home/s/lede/feeds/packages/lang/golang/golang' time: package/feeds/packages/golang/host-compile#0.25#0.29#0.50 make[2]: Entering directory '/home/s/lede/package/libs/toolchain' echo "libc" >> /home/s/lede/staging_dir/target-x86_64_musl/pkginfo/toolchain.default.install echo "libgcc" >> /home/s/lede/staging_dir/target-x86_64_musl/pkginfo/toolchain.default.install echo "libstdcpp" >> /home/s/lede/staging_dir/target-x86_64_musl/pkginfo/toolchain.default.install echo "libpthread" >> /home/s/lede/staging_dir/target-x86_64_musl/pkginfo/toolchain.default.install echo "librt" >> /home/s/lede/staging_dir/target-x86_64_musl/pkginfo/toolchain.default.install make[2]: Leaving directory '/home/s/lede/package/libs/toolchain' time: package/libs/toolchain/compile#0.11#0.03#0.14 make[2]: Entering directory '/home/s/lede/package/system/ca-certificates' mkdir -p /home/s/lede/dl SHELL= flock /home/s/lede/tmp/.ca-certificates_20210119.tar.xz.flock -c ' /home/s/lede/scripts/downlo ad.pl "/home/s/lede/dl" "ca-certificates_20210119.tar.xz" "daa3afae563711c30a0586ddae4336e8e3974c2b627faaca 404c4e0141b64665" "" "@DEBIAN/pool/main/c/ca-certificates" ' echo "ca-bundle" >> /home/s/lede/staging_dir/target-x86_64_musl/pkginfo/ca-certificates.default.install echo "ca-certificates" >> /home/s/lede/staging_dir/target-x86_64_musl/pkginfo/ca-certificates.default.insta ll make[2]: Leaving directory '/home/s/lede/package/system/ca-certificates' time: package/system/ca-certificates/compile#0.14#0.03#0.17 make[2]: Entering directory '/home/s/lede/package/feeds/packages/ServerStatus-Client' make[2]: Leaving directory '/home/s/lede/package/feeds/packages/ServerStatus-Client' time: package/feeds/packages/ServerStatus-Client/compile#0.10#0.02#0.12 make[1]: Leaving directory '/home/s/lede' s@s-virtual-machine:~/lede$ `

在你的编译目录`/bin/packages/x86_64/base` 下面搜索一下 server 相关关键词，看看有没有对应的ipk 文件

**Comment by ReibyouGennsei** [comment]
搜索过了，没有跟server有关的ipk

**Comment by v03413** [comment]
> 搜索过了，没有跟server有关的ipk
[ServerStatus-Client_0.15-34_x86_64.ipk.tar.gz](https://github.com/v03413/ServerStatus-Client/files/9350924/ServerStatus-Client_0.15-34_x86_64.ipk.tar.gz)

那试试这个我之前编译的版本，也是X86；releases 是对应直接二进制文件，可直接在x86 64平台运行

**Comment by ReibyouGennsei** [comment]
太感谢了，完美运行
