### ISSUE TITLE
请问大佬可以帮忙编译一份MTK的版本嘛？

### ISSUE THREAD

**Issue by itgoyo** [v03413/ServerStatus-Client#4]
MediaTek MT7621

请问大佬可以编译一份新路由3(Newifi-D2)的版本么,因为确实对openwrt编译不太熟悉，简单尝试了一下，也没太明白怎么整，实在是抱歉过来打扰您

<img width="937" alt="image" src="https://user-images.githubusercontent.com/23348551/195141078-4b158146-3b86-4090-a3e7-917878cbab62.png">

**Comment by v03413** [comment]
这个U的路由器我记得也不少，我建议你在自己型号编译完成之后，再编译这个插件。

**Comment by itgoyo** [comment]
好嘞，感谢回复
