### ISSUE TITLE
安卓手机好像能用

### ISSUE THREAD

**Issue by gxusb** [v03413/ServerStatus-Client#5]
就是磁盘信息不正确
<img width="1172" alt="image" src="https://user-images.githubusercontent.com/105532932/200160976-70375eaa-48d7-4e46-92d2-549d110b7f8a.png">
![Screenshot_2022-11-06-16-25-50-534_com omarea vtools-edit](https://user-images.githubusercontent.com/105532932/200161370-7a43606b-1bb5-4399-b03b-d94f71b01657.png)

**Comment by v03413** [comment]
> 就是磁盘信息不正确 <img alt="image" width="1172" src="https://user-images.githubusercontent.com/105532932/200160976-70375eaa-48d7-4e46-92d2-549d110b7f8a.png">

我当初用安卓 linux deplay里面装debian跑，的确能用；如果安卓直接 armv8直接跑的话，应该也行，但这个磁盘信息估计应该是安卓分区或者哪里有问题。

**Comment by gxusb** [comment]
我去编译下安卓可执行文件看看

**Comment by v03413** [comment]
磁盘信息获取主要依赖：github.com/shirou/gopsutil/disk

**Comment by gxusb** [comment]
> 磁盘信息获取主要依赖：github.com/shirou/gopsutil/disk

<img width="1161" alt="image" src="https://user-images.githubusercontent.com/105532932/200161895-7bebbfc1-26e8-4eac-acf7-71158bf2f66f.png">
编译安卓的这都用不了

**Comment by v03413** [comment]
> > 磁盘信息获取主要依赖：github.com/shirou/gopsutil/disk
> 
> <img alt="image" width="1161" src="https://user-images.githubusercontent.com/105532932/200161895-7bebbfc1-26e8-4eac-acf7-71158bf2f66f.png">
> 
> 编译安卓的这都用不了

如果有时间的话，你可以把编译流程，运行环境、运行方法具体贴下，我有空看看什么问题
